services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: