"""allow Product.image_link to be nullable

Revision ID: 168d67f19d89
Revises: 337192a89544
Create Date: 2025-10-29 14:37:28.705267

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "168d67f19d89"
down_revision: Union[str, Sequence[str], None] = "337192a89544"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "image_link", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "image_link", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
