"""add TimestampMixin to Product

Revision ID: 2625497230bb
Revises: ffb4aeb0ada1
Create Date: 2025-10-26 13:13:34.461447

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2625497230bb"
down_revision: Union[str, Sequence[str], None] = "ffb4aeb0ada1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Run updated_at before to have updated_at < created_at
    op.add_column("product", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE product set updated_at = NOW()")
    op.alter_column("product", "updated_at", nullable=False)

    op.add_column("product", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE product set created_at = NOW()")
    op.alter_column("product", "created_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "updated_at")
    op.drop_column("product", "created_at")
    # ### end Alembic commands ###
