"""remove product unique constraint

Revision ID: 32759ca08993
Revises: e5e30f2d3b29
Create Date: 2025-11-06 09:05:20.834991

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32759ca08993"
down_revision: Union[str, Sequence[str], None] = "e5e30f2d3b29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("product_source_external_id_key"), "product", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("product_source_external_id_key"),
        "product",
        ["source", "external_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
