"""add external sync metadata

Revision ID: 337192a89544
Revises: 24282d6fb664
Create Date: 2025-10-29 14:23:04.922290

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "337192a89544"
down_revision: Union[str, Sequence[str], None] = "24282d6fb664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_db_sync_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_synced_listing_id", sa.Integer(), nullable=False),
        sa.Column("last_sync_timestamp", sa.DateTime(), nullable=False),
        sa.Column("total_synced", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "product", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "search_vector", existing_type=postgresql.TSVECTOR(), nullable=False
    )
    op.drop_table("external_db_sync_metadata")
    # ### end Alembic commands ###
