"""add css trending queries and products sync

Revision ID: 78e6452dded4
Revises: 168d67f19d89
Create Date: 2025-11-01 09:06:06.986191

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78e6452dded4"
down_revision: Union[str, Sequence[str], None] = "168d67f19d89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###op.create_unique_constraint(None, "trending_queries", ["query_text"])
    op.create_unique_constraint(None, "trending_queries", ["query_text"])

    op.create_table(
        "trending_query_css_sync",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_text", sa.String(), nullable=False),
        sa.Column("css_source", sa.String(), nullable=False),
        sa.Column("last_sync", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_text"], ["trending_queries.query_text"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("query_text", "css_source", name="uq_query_css"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trending_queries", type_="unique")
    op.drop_table("trending_query_css_sync")
    # ### end Alembic commands ###
