"""fix popularity type

Revision ID: be36a064e9b3
Revises: fdcba92d8ec6
Create Date: 2025-10-24 14:20:06.714332

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be36a064e9b3"
down_revision: Union[str, Sequence[str], None] = "fdcba92d8ec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE trending_queries
        ALTER COLUMN popularity TYPE INTEGER
        USING popularity::integer
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE trending_queries
        ALTER COLUMN popularity TYPE VARCHAR
        USING popularity::text
    """)
    # ### end Alembic commands ###
