"""make brand nullable

Revision ID: e5e30f2d3b29
Revises: a349d1e5eb89
Create Date: 2025-11-05 06:46:39.729074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5e30f2d3b29"
down_revision: Union[str, Sequence[str], None] = "a349d1e5eb89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "brand", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "brand", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
