"""add idealo popularity

Revision ID: fdcba92d8ec6
Revises: fa6a0d350491
Create Date: 2025-10-24 12:33:00.123489

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdcba92d8ec6"
down_revision: Union[str, Sequence[str], None] = "fa6a0d350491"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trending_queries", sa.Column("popularity", sa.String(), nullable=True)
    )
    op.execute("UPDATE trending_queries SET popularity = 0")
    op.alter_column("trending_queries", "popularity", nullable=False)

    op.add_column("trending_queries", sa.Column("locale", sa.String(), nullable=True))
    op.execute("UPDATE trending_queries SET locale = 'fr_FR'")
    op.alter_column("trending_queries", "locale", nullable=False)

    op.drop_column("trending_queries", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trending_queries",
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("trending_queries", "locale")
    op.drop_column("trending_queries", "popularity")
    # ### end Alembic commands ###
